const carpetPalette = [
  {
    "index": 0,
    "id": "black_carpet",
    "pathId": "wool_colored_black",
    "average": [20, 21, 25],
    "hasSemitransparentPixel": false,
  },
  {
    "index": 1,
    "id": "blue_carpet",
    "pathId": "wool_colored_blue",
    "average": [53, 57, 157],
    "hasSemitransparentPixel": false,
  },
  {
    "index": 2,
    "id": "brown_carpet",
    "pathId": "wool_colored_brown",
    "average": [114, 71, 40],
    "hasSemitransparentPixel": false,
  },
  {
    "index": 3,
    "id": "cyan_carpet",
    "pathId": "wool_colored_cyan",
    "average": [21, 137, 145],
    "hasSemitransparentPixel": false,
  },
  {
    "index": 4,
    "id": "gray_carpet",
    "pathId": "wool_colored_gray",
    "average": [62, 68, 71],
    "hasSemitransparentPixel": false,
  },
  {
    "index": 5,
    "id": "green_carpet",
    "pathId": "wool_colored_green",
    "average": [84, 109, 27],
    "hasSemitransparentPixel": false,
  },
  {
    "index": 6,
    "id": "light_blue_carpet",
    "pathId": "wool_colored_light_blue",
    "average": [58, 175, 217],
    "hasSemitransparentPixel": false,
  },
  {
    "index": 7,
    "id": "lime_carpet",
    "pathId": "wool_colored_lime",
    "average": [112, 185, 25],
    "hasSemitransparentPixel": false,
  },
  {
    "index": 8,
    "id": "magenta_carpet",
    "pathId": "wool_colored_magenta",
    "average": [189, 68, 179],
    "hasSemitransparentPixel": false,
  },
  {
    "index": 9,
    "id": "orange_carpet",
    "pathId": "wool_colored_orange",
    "average": [240, 118, 19],
    "hasSemitransparentPixel": false,
  },
  {
    "index": 10,
    "id": "pink_carpet",
    "pathId": "wool_colored_pink",
    "average": [237, 141, 172],
    "hasSemitransparentPixel": false,
  },
  {
    "index": 11,
    "id": "purple_carpet",
    "pathId": "wool_colored_purple",
    "average": [121, 42, 172],
    "hasSemitransparentPixel": false,
  },
  {
    "index": 12,
    "id": "red_carpet",
    "pathId": "wool_colored_red",
    "average": [160, 39, 34],
    "hasSemitransparentPixel": false,
  },
  {
    "index": 13,
    "id": "white_carpet",
    "pathId": "wool_colored_white",
    "average": [233, 236, 236],
    "hasSemitransparentPixel": false,
  },
  {
    "index": 14,
    "id": "yellow_carpet",
    "pathId": "wool_colored_yellow",
    "average": [248, 197, 39],
    "hasSemitransparentPixel": false,
  },
];