name: colorify
description: "A new Flutter project."
publish_to: 'none'
version: 6.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  archive: ^3.6.1
  auto_size_text: ^3.0.0
  dart_minecraft: ^0.6.0
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_svg: ^2.0.10+1
  image: ^4.2.0
  jdenticon_dart: ^2.0.0
  nested: ^1.0.0
  nil: ^1.1.1
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
