name: colorify
description: "A new Flutter project."
publish_to: "none"
version: 6.1.5+60101

environment:
  sdk: ^3.8.0

dependencies:
  archive: ^4.0.7
  auto_size_text: ^3.0.0
  dart_minecraft: ^0.6.0
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_svg: ^2.0.10+1
  image: ^4.2.0
  jdenticon_dart: ^2.0.0
  nested: ^1.0.0
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^12.0.0+1
  provider: ^6.1.4
  shared_preferences: ^2.3.2
  sizer: ^3.0.5
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  vector_math: ^2.1.4
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/me.png
    - assets/sponsor.jpg
    - assets/acknowledgement/
    - assets/sponsors/
    - assets/icons/

  fonts:
    - family: Yellowtail
      fonts:
        - asset: assets/fonts/Yellowtail-Regular.ttf
