const mapPalette2 = {
  "version": 1,
  "gameVersion": "1.21.3-1.686+60bf22d",
  "data": {
    "minecraft:trapdoor": "#8f7748",
    "minecraft:pink_tulip": "#007c00",
    "minecraft:budding_amethyst": "#995acd",
    "minecraft:light_blue_concrete_powder": "#6699d8",
    "minecraft:gravel": "#707070",
    "minecraft:detector_rail": "#0",
    "minecraft:cyan_terracotta": "#575c5c",
    "minecraft:hard_pink_stained_glass": "#f27fa5",
    //"minecraft:light_gray_candle": "#999999",
    "minecraft:nether_gold_ore": "#700200",
    "minecraft:polished_basalt": "#191919",
    //"minecraft:blue_candle": "#334cb2",
    "minecraft:dark_oak_wood": "#664c33",
    "minecraft:tuff_brick_wall": "#392923",
    "minecraft:hard_glass_pane": "#0",
    "minecraft:dead_brain_coral_fan": "#4c4c4c",
    "minecraft:acacia_standing_sign": "#d87f33",
    "minecraft:acacia_wall_sign": "#d87f33",
    "minecraft:bamboo_pressure_plate": "#e5e533",
    "minecraft:melon_block": "#7fcc19",
    "minecraft:red_wool": "#993333",
    "minecraft:cornflower": "#007c00",
    // "minecraft:waxed_cut_copper_stairs": "#d87f33",
    // "minecraft:element_93": "#7f4ccc",
    "minecraft:gold_ore": "#707070",
    "minecraft:birch_standing_sign": "#f7e9a3",
    // "minecraft:element_98": "#7f4ccc",
    "minecraft:red_nether_brick": "#700200",
    // "minecraft:oxidized_cut_copper_stairs": "#167e86",
    "minecraft:warped_door": "#3a8e8c",
    "minecraft:polished_granite_stairs": "#976d4d",
    "minecraft:red_mushroom_block": "#993333",
    "minecraft:blue_carpet": "#334cb2",
    "minecraft:bamboo_block": "#e5e533",
    "minecraft:deepslate_bricks": "#646464",
    // "minecraft:waxed_copper": "#d87f33",
    "minecraft:white_wool": "#ffffff",
    "minecraft:wooden_door": "#8f7748",
    "minecraft:piston_arm_collision": "#707070",
    "minecraft:end_bricks": "#f7e9a3",
    "minecraft:sculk_shrieker": "#0d1217",
    "minecraft:bamboo_mosaic_stairs": "#e5e533",
    "minecraft:vine": "#4e711e",
    // "minecraft:waxed_oxidized_chiseled_copper": "#167e86",
    "minecraft:white_tulip": "#007c00",
    "minecraft:granite": "#976d4d",
    "minecraft:lime_glazed_terracotta": "#7fcc19",
    "minecraft:polished_tuff_slab": "#392923",
    "minecraft:brown_mushroom": "#664c33",
    // "minecraft:cut_copper_stairs": "#d87f33",
    // "minecraft:element_20": "#33a5c1",
    "minecraft:blue_stained_glass_pane": "#0",
    // "minecraft:element_0": "#000000",
    // "minecraft:exposed_copper_door": "#876b62",
    "minecraft:blackstone_double_slab": "#191919",
    "minecraft:spruce_standing_sign": "#815631",
    // "minecraft:element_118": "#ce7cfc",
    "minecraft:fence_gate": "#8f7748",
    "minecraft:deepslate_tile_slab": "#646464",
    "minecraft:powder_snow": "#ffffff",
    //"minecraft:magenta_candle": "#b24cd8",
    "minecraft:deepslate_tile_double_slab": "#646464",
    "minecraft:calcite": "#d1b1a1",
    "minecraft:gray_terracotta": "#392923",
    "minecraft:cyan_carpet": "#4c7f99",
    "minecraft:cyan_stained_glass": "#4c7f99",
    "minecraft:dark_oak_button": "#0",
    // "minecraft:deepslate_copper_ore": "#646464",
    "minecraft:stone_brick_stairs": "#707070",
    "minecraft:spruce_pressure_plate": "#815631",
    "minecraft:diamond_ore": "#707070",
    // "minecraft:waxed_oxidized_cut_copper": "#167e86",
    "minecraft:gray_concrete": "#4c4c4c",
    "minecraft:cobblestone_slab": "#707070",
    "minecraft:green_terracotta": "#4c522a",
    "minecraft:hard_purple_stained_glass_pane": "#0",
    // "minecraft:element_73": "#828282",
    // "minecraft:waxed_copper_trapdoor": "#a7a7a7",
    "minecraft:nether_brick_stairs": "#700200",
    "minecraft:hard_blue_stained_glass_pane": "#0",
    "minecraft:yellow_shulker_box": "#e5e533",
    // "minecraft:chiseled_copper": "#d87f33",
    "minecraft:granite_stairs": "#976d4d",
    "minecraft:gray_wool": "#4c4c4c",
    "minecraft:green_concrete_powder": "#667f33",
    "minecraft:lime_stained_glass": "#7fcc19",
    // "minecraft:oxidized_copper_bulb": "#167e86",
    "minecraft:cobbled_deepslate_stairs": "#646464",
    // "minecraft:waxed_exposed_copper": "#876b62",
    "minecraft:stripped_acacia_wood": "#4c4c4c",
    // "minecraft:element_16": "#7ab244",
    "minecraft:jungle_button": "#0",
    "minecraft:dead_bubble_coral_fan": "#4c4c4c",
    "minecraft:powered_repeater": "#0",
    "minecraft:spruce_stairs": "#815631",
    "minecraft:loom": "#8f7748",
    "minecraft:hard_green_stained_glass_pane": "#0",
    // "minecraft:element_104": "#828282",
    "minecraft:yellow_stained_glass": "#e5e533",
    "minecraft:jungle_door": "#976d4d",
    "minecraft:darkoak_wall_sign": "#664c33",
    "minecraft:diorite": "#fffcf5",
    // "minecraft:oxidized_double_cut_copper_slab": "#167e86",
    "minecraft:info_update2": "#976d4d",
    "minecraft:dripstone_block": "#4c3223",
    //"minecraft:gray_candle_cake": "#0",
    // "minecraft:exposed_copper_trapdoor": "#a7a7a7",
    "minecraft:blue_terracotta": "#4c3e5c",
    "minecraft:hanging_roots": "#007c00",
    //"minecraft:red_candle_cake": "#0",
    "minecraft:hard_light_blue_stained_glass_pane": "#0",
    "minecraft:cherry_pressure_plate": "#d1b1a1",
    "minecraft:hard_brown_stained_glass": "#664c33",
    "minecraft:cherry_hanging_sign": "#a04d4e",
    "minecraft:yellow_wool": "#e5e533",
    //"minecraft:black_candle_cake": "#0",
    "minecraft:crimson_wall_sign": "#700200",
    "minecraft:polished_blackstone_brick_stairs": "#191919",
    "minecraft:gray_carpet": "#4c4c4c",
    "minecraft:dark_oak_door": "#664c33",
    "minecraft:wheat": "#007c00",
    // "minecraft:element_46": "#828282",
    "minecraft:grindstone": "#a7a7a7",
    "minecraft:oak_fence": "#8f7748",
    "minecraft:yellow_stained_glass_pane": "#0",
    "minecraft:dark_oak_slab": "#664c33",
    "minecraft:honeycomb_block": "#d87f33",
    "minecraft:end_gateway": "#191919",
    "minecraft:azure_bluet": "#007c00",
    "minecraft:stone_stairs": "#707070",
    "minecraft:beacon": "#5cdbd5",
    "minecraft:polished_blackstone_brick_wall": "#191919",
    "minecraft:snow_layer": "#ffffff",
    "minecraft:hard_pink_stained_glass_pane": "#0",
    "minecraft:white_carpet": "#ffffff",
    //"minecraft:black_candle": "#191919",
    "minecraft:cactus": "#007c00",
    "minecraft:glow_frame": "#0",
    "minecraft:mud_brick_double_slab": "#876b62",
    "minecraft:bamboo_mosaic_slab": "#e5e533",
    "minecraft:bamboo_fence": "#e5e533",
    "minecraft:prismarine_bricks_stairs": "#5cdbd5",
    "minecraft:crimson_hyphae": "#5c191d",
    "minecraft:black_terracotta": "#251610",
    "minecraft:red_concrete": "#993333",
    "minecraft:stripped_dark_oak_log": "#664c33",
    "minecraft:hard_orange_stained_glass_pane": "#0",
    // "minecraft:oxidized_copper_grate": "#167e86",
    "minecraft:jungle_log": "#976d4d",
    "minecraft:bubble_coral_fan": "#92bc58",
    "minecraft:bamboo_slab": "#e5e533",
    "minecraft:lit_redstone_ore": "#707070",
    "minecraft:nether_wart": "#993333",
    "minecraft:orange_stained_glass_pane": "#0",
    "minecraft:stripped_mangrove_wood": "#993333",
    "minecraft:lime_shulker_box": "#7fcc19",
    "minecraft:hard_black_stained_glass_pane": "#0",
    "minecraft:lily_of_the_valley": "#007c00",
    "minecraft:blue_orchid": "#007c00",
    "minecraft:undyed_shulker_box": "#995acd",
    "minecraft:quartz_ore": "#700200",
    "minecraft:info_update": "#976d4d",
    "minecraft:seagrass": "#4040ff",
    "minecraft:tube_coral_fan": "#92bc58",
    "minecraft:unknown": "#0",
    "minecraft:cherry_stairs": "#d1b1a1",
    "minecraft:barrel": "#8f7748",
    "minecraft:big_dripleaf": "#007c00",
    "minecraft:quartz_slab": "#fffcf5",
    "minecraft:fire_coral_block": "#993333",
    // "minecraft:waxed_exposed_cut_copper_slab": "#876b62",
    "minecraft:dead_horn_coral": "#4c4c4c",
    "minecraft:redstone_lamp": "#0",
    // "minecraft:element_68": "#ef9ee2",
    "minecraft:mossy_cobblestone": "#707070",
    // "minecraft:element_113": "#b2aa8c",
    "minecraft:blue_stained_glass": "#334cb2",
    "minecraft:cake": "#0",
    "minecraft:stripped_oak_wood": "#8f7748",
    "minecraft:deepslate": "#646464",
    "minecraft:dark_oak_double_slab": "#664c33",
    "minecraft:double_stone_block_slab3": "#f7e9a3",
    "minecraft:stripped_crimson_hyphae": "#5c191d",
    "minecraft:dark_oak_hanging_sign": "#664c33",
    "minecraft:green_concrete": "#667f33",
    "minecraft:magenta_carpet": "#b24cd8",
    "minecraft:pitcher_crop": "#007c00",
    "minecraft:brown_wool": "#664c33",
    "minecraft:pink_wool": "#f27fa5",
    "minecraft:warped_standing_sign": "#4c7f99",
    "minecraft:deadbush": "#8f7748",
    "minecraft:ender_chest": "#707070",
    // "minecraft:waxed_exposed_chiseled_copper": "#876b62",
    "minecraft:tuff_slab": "#392923",
    "minecraft:redstone_wire": "#0",
    "minecraft:warped_pressure_plate": "#4c7f99",
    //"minecraft:green_candle_cake": "#0",
    "minecraft:diamond_block": "#5cdbd5",
    // "minecraft:exposed_copper_bulb": "#876b62",
    "minecraft:oak_stairs": "#8f7748",
    "minecraft:hard_gray_stained_glass": "#4c4c4c",
    // "minecraft:waxed_weathered_cut_copper": "#3a8e8c",
    "minecraft:oak_log": "#8f7748",
    "minecraft:andesite": "#707070",
    "minecraft:brown_stained_glass_pane": "#0",
    "minecraft:sculk_vein": "#0d1217",
    "minecraft:pink_stained_glass_pane": "#0",
    // "minecraft:exposed_double_cut_copper_slab": "#876b62",
    //"minecraft:candle_cake": "#0",
    "minecraft:magenta_shulker_box": "#b24cd8",
    "minecraft:purple_terracotta": "#7a4958",
    "minecraft:packed_ice": "#a0a0ff",
    "minecraft:iron_bars": "#0",
    // "minecraft:oxidized_cut_copper": "#167e86",
    "minecraft:polished_granite": "#976d4d",
    "minecraft:light_blue_stained_glass": "#6699d8",
    "minecraft:fern": "#92bc58",
    // "minecraft:element_39": "#828282",
    "minecraft:packed_mud": "#976d4d",
    // "minecraft:element_21": "#828282",
    //"minecraft:light_blue_candle_cake": "#0",
    // "minecraft:element_1": "#7ab244",
    "minecraft:poppy": "#007c00",
    "minecraft:moss_carpet": "#667f33",
    "minecraft:crimson_stairs": "#943f61",
    "minecraft:green_stained_glass_pane": "#0",
    "minecraft:warped_fungus": "#4c7f99",
    // "minecraft:element_102": "#7f4ccc",
    // "minecraft:copper_ore": "#707070",
    //"minecraft:gray_candle": "#4c4c4c",
    "minecraft:polished_deepslate_slab": "#646464",
    "minecraft:bamboo_door": "#e5e533",
    "minecraft:black_concrete_powder": "#191919",
    "minecraft:amethyst_block": "#995acd",
    "minecraft:melon_stem": "#007c00",
    "minecraft:gold_block": "#faee4d",
    "minecraft:stripped_oak_log": "#8f7748",
    // "minecraft:flower_pot": "#0",
    "minecraft:chiseled_bookshelf": "#8f7748",
    "minecraft:jungle_fence": "#976d4d",
    "minecraft:spruce_log": "#815631",
    "minecraft:polished_deepslate_stairs": "#646464",
    "minecraft:hard_lime_stained_glass": "#7fcc19",
    "minecraft:pink_terracotta": "#a04d4e",
    // "minecraft:waxed_weathered_copper_door": "#3a8e8c",
    "minecraft:carved_pumpkin": "#d87f33",
    "minecraft:yellow_flower": "#007c00",
    "minecraft:short_grass": "#92bc58",
    "minecraft:lapis_block": "#4a80ff",
    // "minecraft:weathered_chiseled_copper": "#3a8e8c",
    "minecraft:small_amethyst_bud": "#995acd",
    "minecraft:activator_rail": "#0",
    "minecraft:podzol": "#815631",
    "minecraft:mangrove_button": "#0",
    "minecraft:iron_trapdoor": "#a7a7a7",
    "minecraft:potatoes": "#007c00",
    "minecraft:large_amethyst_bud": "#995acd",
    "minecraft:muddy_mangrove_roots": "#815631",
    "minecraft:hard_light_blue_stained_glass": "#6699d8",
    "minecraft:trial_spawner": "#707070",
    "minecraft:stripped_jungle_wood": "#976d4d",
    "minecraft:dead_tube_coral_block": "#4c4c4c",
    "minecraft:noteblock": "#8f7748",
    "minecraft:tuff": "#392923",
    "minecraft:reserved6": "#976d4d",
    "minecraft:soul_torch": "#0",
    "minecraft:quartz_bricks": "#fffcf5",
    "minecraft:mangrove_log": "#993333",
    "minecraft:sandstone_slab": "#f7e9a3",
    "minecraft:white_shulker_box": "#ffffff",
    "minecraft:raw_gold_block": "#faee4d",
    "minecraft:allium": "#007c00",
    "minecraft:cracked_polished_blackstone_bricks": "#191919",
    "minecraft:mob_spawner": "#707070",
    // "minecraft:copper_grate": "#d87f33",
    // "minecraft:weathered_double_cut_copper_slab": "#3a8e8c",
    "minecraft:deepslate_tiles": "#646464",
    "minecraft:black_wool": "#191919",
    "minecraft:lava": "#ff0000",
    "minecraft:acacia_fence_gate": "#d87f33",
    //"minecraft:cyan_candle_cake": "#0",
    //"minecraft:orange_candle": "#d87f33",
    "minecraft:colored_torch_bp": "#0",
    "minecraft:scaffolding": "#f7e9a3",
    "minecraft:powered_comparator": "#0",
    // "minecraft:waxed_oxidized_cut_copper_slab": "#167e86",
    "minecraft:warped_wall_sign": "#4c7f99",
    "minecraft:spruce_fence": "#815631",
    "minecraft:hard_yellow_stained_glass_pane": "#0",
    "minecraft:hard_green_stained_glass": "#667f33",
    "minecraft:dark_oak_sapling": "#007c00",
    "minecraft:pink_petals": "#0",
    "minecraft:soul_fire": "#6699d8",
    "minecraft:pink_carpet": "#f27fa5",
    "minecraft:mangrove_double_slab": "#993333",
    "minecraft:brown_carpet": "#664c33",
    // "minecraft:oxidized_copper_trapdoor": "#a7a7a7",
    "minecraft:light_gray_stained_glass": "#999999",
    "minecraft:brain_coral": "#92bc58",
    "minecraft:white_stained_glass": "#ffffff",
    "minecraft:obsidian": "#191919",
    "minecraft:chest": "#8f7748",
    "minecraft:dead_bubble_coral_block": "#4c4c4c",
    "minecraft:light_gray_stained_glass_pane": "#0",
    "minecraft:blackstone_slab": "#191919",
    "minecraft:stripped_spruce_wood": "#815631",
    "minecraft:cauldron": "#707070",
    "minecraft:glowingobsidian": "#191919",
    "minecraft:deepslate_brick_wall": "#646464",
    "minecraft:darkoak_standing_sign": "#664c33",
    // "minecraft:waxed_exposed_copper_grate": "#876b62",
    "minecraft:tube_coral_block": "#334cb2",
    "minecraft:acacia_planks": "#d87f33",
    "minecraft:jungle_wall_sign": "#976d4d",
    "minecraft:end_brick_stairs": "#f7e9a3",
    // "minecraft:element_85": "#f9c654",
    "minecraft:polished_blackstone_double_slab": "#191919",
    "minecraft:orange_carpet": "#d87f33",
    // "minecraft:exposed_copper": "#876b62",
    "minecraft:polished_deepslate_double_slab": "#646464",
    "minecraft:nether_brick_slab": "#700200",
    "minecraft:heavy_weighted_pressure_plate": "#a7a7a7",
    "minecraft:stone_button": "#0",
    // "minecraft:element_89": "#7f4ccc",
    "minecraft:pitcher_plant": "#007c00",
    // "minecraft:element_101": "#7f4ccc",
    // "minecraft:waxed_copper_bulb": "#d87f33",
    "minecraft:sponge": "#e5e533",
    "minecraft:andesite_stairs": "#707070",
    "minecraft:bone_block": "#f7e9a3",
    "minecraft:normal_stone_stairs": "#707070",
    "minecraft:warped_hanging_sign": "#4c7f99",
    "minecraft:frame": "#0",
    "minecraft:smoker": "#707070",
    "minecraft:hardened_clay": "#d87f33",
    "minecraft:birch_hanging_sign": "#f7e9a3",
    "minecraft:polished_tuff_wall": "#392923",
    "minecraft:unlit_redstone_torch": "#0",
    "minecraft:stripped_jungle_log": "#976d4d",
    "minecraft:stonecutter": "#707070",
    "minecraft:unpowered_repeater": "#0",
    "minecraft:oak_sapling": "#007c00",
    "minecraft:light_gray_terracotta": "#876b62",
    "minecraft:pink_stained_glass": "#f27fa5",
    "minecraft:hard_magenta_stained_glass_pane": "#0",
    "minecraft:brown_stained_glass": "#664c33",
    "minecraft:fire_coral": "#92bc58",
    "minecraft:stone": "#707070",
    "minecraft:birch_log": "#f7e9a3",
    // "minecraft:element_99": "#7f4ccc",
    "minecraft:cobbled_deepslate": "#646464",
    "minecraft:orange_stained_glass": "#d87f33",
    "minecraft:orange_wool": "#d87f33",
    "minecraft:polished_blackstone_brick_double_slab": "#191919",
    "minecraft:bubble_coral_block": "#995acd",
    "minecraft:crimson_double_slab": "#700200",
    "minecraft:kelp": "#4040ff",
    "minecraft:underwater_torch": "#0",
    "minecraft:respawn_anchor": "#191919",
    "minecraft:light_gray_concrete": "#999999",
    "minecraft:dark_oak_stairs": "#664c33",
    "minecraft:purple_stained_glass_pane": "#0",
    //"minecraft:green_candle": "#667f33",
    "minecraft:birch_wood": "#f7e9a3",
    // "minecraft:element_43": "#828282",
    "minecraft:hay_block": "#e5e533",
    "minecraft:red_stained_glass": "#993333",
    "minecraft:purple_shulker_box": "#995acd",
    "minecraft:polished_tuff_double_slab": "#392923",
    "minecraft:suspicious_gravel": "#707070",
    "minecraft:heavy_core": "#a7a7a7",
    "minecraft:jungle_wood": "#976d4d",
    // "minecraft:oxidized_copper_door": "#167e86",
    // "minecraft:waxed_weathered_copper": "#3a8e8c",
    "minecraft:deepslate_brick_slab": "#646464",
    "minecraft:flowering_azalea": "#007c00",
    "minecraft:invisible_bedrock": "#0",
    "minecraft:oak_leaves": "#3f5c18",
    "minecraft:brain_coral_fan": "#92bc58",
    "minecraft:bamboo_stairs": "#e5e533",
    "minecraft:torch": "#0",
    "minecraft:glow_lichen": "#7fa796",
    // "minecraft:copper_trapdoor": "#a7a7a7",
    //"minecraft:red_candle": "#993333",
    "minecraft:mud_brick_wall": "#876b62",
    "minecraft:honey_block": "#d87f33",
    "minecraft:cherry_trapdoor": "#d1b1a1",
    "minecraft:brown_concrete": "#664c33",
    "minecraft:lit_pumpkin": "#d87f33",
    "minecraft:pink_concrete": "#f27fa5",
    "minecraft:yellow_glazed_terracotta": "#e5e533",
    "minecraft:smooth_basalt": "#191919",
    "minecraft:warped_planks": "#3a8e8c",
    "minecraft:piston": "#707070",
    "minecraft:cherry_fence": "#d1b1a1",
    "minecraft:mangrove_planks": "#993333",
    "minecraft:hard_light_gray_stained_glass_pane": "#0",
    "minecraft:red_terracotta": "#8e3c2e",
    // "minecraft:weathered_copper_grate": "#3a8e8c",
    // "minecraft:element_77": "#828282",
    "minecraft:water": "#1e5af5",
    // "minecraft:weathered_copper_trapdoor": "#a7a7a7",
    "minecraft:spruce_button": "#0",
    "minecraft:wall_banner": "#8f7748",
    "minecraft:dead_fire_coral_block": "#4c4c4c",
    "minecraft:magenta_wool": "#b24cd8",
    // "minecraft:waxed_weathered_copper_grate": "#3a8e8c",
    // "minecraft:waxed_weathered_copper_bulb": "#3a8e8c",
    "minecraft:verdant_froglight": "#7fa796",
    "minecraft:magenta_glazed_terracotta": "#b24cd8",
    "minecraft:wall_sign": "#8f7748",
    "minecraft:mangrove_slab": "#993333",
    "minecraft:infested_deepslate": "#646464",
    "minecraft:orange_glazed_terracotta": "#d87f33",
    // "minecraft:birch_sapling": "#007c00",
    "minecraft:client_request_placeholder_block": "#0",
    "minecraft:hard_brown_stained_glass_pane": "#0",
    "minecraft:torchflower": "#007c00",
    "minecraft:spore_blossom": "#007c00",
    "minecraft:waterlily": "#007c00",
    "minecraft:stripped_dark_oak_wood": "#664c33",
    "minecraft:emerald_block": "#00d93a",
    "minecraft:suspicious_sand": "#f7e9a3",
    "minecraft:ancient_debris": "#191919",
    "minecraft:jungle_leaves": "#3f5c18",
    "minecraft:dark_oak_planks": "#664c33",
    "minecraft:conduit": "#5cdbd5",
    "minecraft:anvil": "#a7a7a7",
    "minecraft:polished_andesite": "#707070",
    "minecraft:purple_stained_glass": "#995acd",
    "minecraft:lightning_rod": "#d87f33",
    "minecraft:acacia_leaves": "#3f5c18",
    "minecraft:barrier": "#0",
    "minecraft:nether_brick_fence": "#700200",
    "minecraft:black_stained_glass_pane": "#0",
    "minecraft:magenta_concrete": "#b24cd8",
    "minecraft:cobblestone_wall": "#707070",
    "minecraft:light_blue_stained_glass_pane": "#0",
    "minecraft:deepslate_brick_double_slab": "#646464",
    // "minecraft:element_91": "#7f4ccc",
    "minecraft:spruce_double_slab": "#815631",
    "minecraft:red_sandstone": "#d87f33",
    "minecraft:dark_oak_log": "#664c33",
    "minecraft:oak_planks": "#8f7748",
    "minecraft:redstone_ore": "#707070",
    "minecraft:acacia_hanging_sign": "#d87f33",
    // "minecraft:element_41": "#828282",
    "minecraft:ochre_froglight": "#f7e9a3",
    "minecraft:polished_blackstone_stairs": "#191919",
    "minecraft:tuff_wall": "#392923",
    "minecraft:mangrove_pressure_plate": "#993333",
    "minecraft:observer": "#707070",
    "minecraft:pink_glazed_terracotta": "#f27fa5",
    "minecraft:yellow_terracotta": "#ba8524",
    "minecraft:brown_glazed_terracotta": "#664c33",
    //"minecraft:brown_candle_cake": "#0",
    //"minecraft:pink_candle_cake": "#0",
    "minecraft:quartz_block": "#fffcf5",
    "minecraft:redstone_torch": "#0",
    "minecraft:birch_leaves": "#455a2e",
    "minecraft:silver_glazed_terracotta": "#999999",
    "minecraft:cyan_concrete_powder": "#4c7f99",
    // "minecraft:oxidized_copper": "#167e86",
    "minecraft:birch_pressure_plate": "#f7e9a3",
    // "minecraft:element_19": "#567ce5",
    "minecraft:sandstone_stairs": "#f7e9a3",
    // "minecraft:element_49": "#b2aa8c",
    "minecraft:stripped_bamboo_block": "#e5e533",
    "minecraft:birch_fence_gate": "#f7e9a3",
    "minecraft:sculk_catalyst": "#0d1217",
    // "minecraft:element_115": "#b2aa8c",
    "minecraft:cobblestone": "#707070",
    "minecraft:white_concrete_powder": "#ffffff",
    "minecraft:horn_coral": "#92bc58",
    "minecraft:yellow_concrete": "#e5e533",
    "minecraft:oak_double_slab": "#8f7748",
    "minecraft:stripped_warped_stem": "#3a8e8c",
    "minecraft:daylight_detector": "#8f7748",
    "minecraft:smooth_sandstone_stairs": "#f7e9a3",
    "minecraft:jungle_pressure_plate": "#976d4d",
    "minecraft:hard_white_stained_glass": "#ffffff",
    // "minecraft:double_cut_copper_slab": "#d87f33",
    "minecraft:sandstone": "#f7e9a3",
    "minecraft:birch_button": "#0",
    "minecraft:crimson_planks": "#943f61",
    "minecraft:blackstone_wall": "#191919",
    "minecraft:light_weighted_pressure_plate": "#faee4d",
    "minecraft:polished_blackstone": "#191919",
    "minecraft:mycelium": "#995acd",
    // "minecraft:element_72": "#828282",
    "minecraft:bamboo": "#007c00",
    "minecraft:iron_ore": "#707070",
    // "minecraft:waxed_weathered_chiseled_copper": "#3a8e8c",
    // "minecraft:element_17": "#f9c654",
    "minecraft:gray_stained_glass": "#4c4c4c",
    // "minecraft:element_51": "#ba8784",
    "minecraft:sticky_piston_arm_collision": "#707070",
    "minecraft:warped_stairs": "#3a8e8c",
    // "minecraft:element_52": "#ba8784",
    // "minecraft:exposed_cut_copper_slab": "#876b62",
    // "minecraft:waxed_oxidized_copper_grate": "#167e86",
    "minecraft:stonebrick": "#707070",
    // "minecraft:oxidized_chiseled_copper": "#167e86",
    "minecraft:bedrock": "#707070",
    "minecraft:smithing_table": "#8f7748",
    "minecraft:tuff_brick_slab": "#392923",
    "minecraft:rose_bush": "#007c00",
    "minecraft:warped_roots": "#4c7f99",
    "minecraft:small_dripleaf_block": "#007c00",
    "minecraft:green_wool": "#667f33",
    "minecraft:green_carpet": "#667f33",
    //"minecraft:purple_candle_cake": "#0",
    "minecraft:netherite_block": "#191919",
    "minecraft:redstone_block": "#ff0000",
    "minecraft:polished_blackstone_wall": "#191919",
    // "minecraft:waxed_exposed_cut_copper": "#876b62",
    "minecraft:gilded_blackstone": "#191919",
    "minecraft:jungle_hanging_sign": "#976d4d",
    "minecraft:blue_concrete_powder": "#334cb2",
    "minecraft:cherry_wood": "#392923",
    "minecraft:birch_slab": "#f7e9a3",
    "minecraft:end_stone": "#f7e9a3",
    "minecraft:crimson_door": "#943f61",
    "minecraft:jungle_slab": "#976d4d",
    // "minecraft:waxed_oxidized_copper": "#167e86",
    "minecraft:glowstone": "#f7e9a3",
    "minecraft:stone_pressure_plate": "#707070",
    "minecraft:quartz_stairs": "#fffcf5",
    // "minecraft:waxed_exposed_cut_copper_stairs": "#876b62",
    "minecraft:hard_lime_stained_glass_pane": "#0",
    "minecraft:mud_brick_slab": "#876b62",
    "minecraft:cracked_deepslate_tiles": "#646464",
    "minecraft:farmland": "#976d4d",
    "minecraft:rail": "#0",
    "minecraft:soul_lantern": "#a7a7a7",
    "minecraft:carrots": "#007c00",
    "minecraft:acacia_trapdoor": "#d87f33",
    "minecraft:mossy_cobblestone_stairs": "#707070",
    // "minecraft:element_67": "#ef9ee2",
    "minecraft:coral_fan_hang2": "#92bc58",
    "minecraft:polished_deepslate_wall": "#646464",
    // "minecraft:element_66": "#ef9ee2",
    "minecraft:coral_fan_hang3": "#92bc58",
    "minecraft:hard_magenta_stained_glass": "#b24cd8",
    "minecraft:monster_egg": "#707070",
    "minecraft:mangrove_wood": "#993333",
    "minecraft:crafting_table": "#8f7748",
    "minecraft:red_glazed_terracotta": "#993333",
    "minecraft:dark_oak_fence_gate": "#664c33",
    "minecraft:bamboo_mosaic_double_slab": "#e5e533",
    // "minecraft:element_58": "#ef9ee2",
    "minecraft:cherry_button": "#0",
    "minecraft:crimson_nylium": "#bd3031",
    "minecraft:warped_double_slab": "#4c7f99",
    "minecraft:structure_void": "#0",
    "minecraft:purple_concrete": "#995acd",
    "minecraft:bamboo_fence_gate": "#e5e533",
    "minecraft:white_stained_glass_pane": "#0",
    // "minecraft:waxed_exposed_copper_bulb": "#876b62",
    "minecraft:bubble_coral": "#92bc58",
    "minecraft:coal_ore": "#707070",
    "minecraft:polished_blackstone_brick_slab": "#191919",
    // "minecraft:spruce_sapling": "#007c00",
    "minecraft:snow": "#ffffff",
    "minecraft:calibrated_sculk_sensor": "#0d1217",
    "minecraft:yellow_concrete_powder": "#e5e533",
    "minecraft:oak_slab": "#8f7748",
    "minecraft:sand": "#f7e9a3",
    "minecraft:mangrove_standing_sign": "#993333",
    "minecraft:slime": "#7fb238",
    // "minecraft:element_117": "#f9c654",
    "minecraft:azalea_leaves": "#007c00",
    "minecraft:chiseled_polished_blackstone": "#191919",
    "minecraft:bamboo_double_slab": "#e5e533",
    "minecraft:smooth_stone_slab": "#707070",
    "minecraft:green_stained_glass": "#667f33",
    "minecraft:brown_concrete_powder": "#664c33",
    "minecraft:cracked_deepslate_bricks": "#646464",
    "minecraft:pink_concrete_powder": "#f27fa5",
    "minecraft:dead_tube_coral": "#4c4c4c",
    "minecraft:acacia_door": "#d87f33",
    "minecraft:orange_shulker_box": "#d87f33",
    "minecraft:nether_wart_block": "#993333",
    "minecraft:light_blue_glazed_terracotta": "#6699d8",
    "minecraft:golden_rail": "#0",
    "minecraft:lit_furnace": "#707070",
    "minecraft:cherry_door": "#d1b1a1",
    // "minecraft:weathered_cut_copper_stairs": "#3a8e8c",
    "minecraft:acacia_log": "#d87f33",
    "minecraft:flowing_lava": "#ff0000",
    "minecraft:white_terracotta": "#d1b1a1",
    // "minecraft:element_84": "#ba8784",
    "minecraft:crimson_trapdoor": "#700200",
    "minecraft:blue_shulker_box": "#334cb2",
    "minecraft:basalt": "#191919",
    // "minecraft:waxed_weathered_copper_trapdoor": "#a7a7a7",
    "minecraft:hard_cyan_stained_glass": "#4c7f99",
    "minecraft:polished_diorite": "#fffcf5",
    // "minecraft:element_13": "#b2aa8c",
    "minecraft:cyan_glazed_terracotta": "#4c7f99",
    "minecraft:light_blue_terracotta": "#706c8a",
    "minecraft:lit_redstone_lamp": "#0",
    "minecraft:hard_blue_stained_glass": "#334cb2",
    "minecraft:lapis_ore": "#707070",
    // "minecraft:oxidized_cut_copper_slab": "#167e86",
    "minecraft:beehive": "#8f7748",
    "minecraft:hard_purple_stained_glass": "#995acd",
    //"minecraft:yellow_candle_cake": "#0",
    "minecraft:sticky_piston": "#707070",
    "minecraft:medium_amethyst_bud": "#995acd",
    "minecraft:brown_shulker_box": "#664c33",
    "minecraft:pink_shulker_box": "#f27fa5",
    //"minecraft:light_blue_candle": "#6699d8",
    "minecraft:deepslate_tile_stairs": "#646464",
    "minecraft:sculk_sensor": "#0d1217",
    // "minecraft:element_26": "#828282",
    // "minecraft:copper_bulb": "#d87f33",
    // "minecraft:element_6": "#7ab244",
    "minecraft:diorite_stairs": "#fffcf5",
    // "minecraft:element_97": "#7f4ccc",
    "minecraft:spruce_leaves": "#345234",
    "minecraft:red_stained_glass_pane": "#0",
    "minecraft:frog_spawn": "#4040ff",
    // "minecraft:element_111": "#828282",
    "minecraft:red_shulker_box": "#993333",
    "minecraft:dirt_with_roots": "#976d4d",
    "minecraft:stripped_cherry_log": "#d1b1a1",
    "minecraft:bamboo_trapdoor": "#e5e533",
    // "minecraft:copper_door": "#d87f33",
    "minecraft:crimson_button": "#0",
    "minecraft:magenta_concrete_powder": "#b24cd8",
    "minecraft:prismarine_stairs": "#4c7f99",
    "minecraft:iron_door": "#a7a7a7",
    "minecraft:mangrove_trapdoor": "#993333",
    "minecraft:daylight_detector_inverted": "#8f7748",
    "minecraft:jungle_planks": "#976d4d",
    "minecraft:chorus_flower": "#995acd",
    "minecraft:torchflower_crop": "#007c00",
    //"minecraft:lime_candle_cake": "#0",
    "minecraft:coral_fan_hang": "#92bc58",
    "minecraft:mangrove_leaves": "#3f5c18",
    "minecraft:polished_blackstone_button": "#0",
    "minecraft:stripped_birch_wood": "#f7e9a3",
    "minecraft:cracked_nether_bricks": "#700200",
    "minecraft:pumpkin": "#d87f33",
    "minecraft:smooth_stone": "#707070",
    "minecraft:lime_concrete": "#7fcc19",
    // "minecraft:waxed_weathered_cut_copper_slab": "#3a8e8c",
    "minecraft:red_mushroom": "#993333",
    "minecraft:hard_yellow_stained_glass": "#e5e533",
    "minecraft:magenta_terracotta": "#95576c",
    "minecraft:black_carpet": "#191919",
    // "minecraft:exposed_cut_copper_stairs": "#876b62",
    "minecraft:mangrove_stairs": "#993333",
    "minecraft:light_blue_concrete": "#6699d8",
    "minecraft:mangrove_fence_gate": "#993333",
    "minecraft:bubble_column": "#4040ff",
    "minecraft:sunflower": "#007c00",
    "minecraft:allow": "#8f7748",
    "minecraft:gray_concrete_powder": "#4c4c4c",
    "minecraft:bamboo_hanging_sign": "#e5e533",
    "minecraft:wither_rose": "#007c00",
    // "minecraft:copper_block": "#d87f33",
    "minecraft:crimson_fence_gate": "#943f61",
    "minecraft:birch_double_slab": "#f7e9a3",
    // "minecraft:waxed_weathered_double_cut_copper_slab": "#3a8e8c",
    "minecraft:polished_blackstone_bricks": "#191919",
    // "minecraft:cut_copper": "#d87f33",
    "minecraft:frosted_ice": "#a0a0ff",
    "minecraft:spruce_door": "#815631",
    "minecraft:warped_trapdoor": "#4c7f99",
    "minecraft:orange_concrete_powder": "#d87f33",
    "minecraft:flowing_water": "#1e5af5",
    "minecraft:brick_block": "#993333",
    "minecraft:hard_glass": "#0",
    "minecraft:cave_vines": "#007c00",
    "minecraft:magenta_stained_glass_pane": "#0",
    "minecraft:light_blue_carpet": "#6699d8",
    // "minecraft:element_62": "#ef9ee2",
    "minecraft:oak_hanging_sign": "#8f7748",
    "minecraft:oak_wood": "#8f7748",
    // "minecraft:waxed_exposed_double_cut_copper_slab": "#876b62",
    // "minecraft:waxed_oxidized_copper_trapdoor": "#a7a7a7",
    "minecraft:jukebox": "#976d4d",
    "minecraft:stripped_cherry_wood": "#a04d4e",
    "minecraft:jigsaw": "#999999",
    "minecraft:acacia_pressure_plate": "#d87f33",
    "minecraft:border_block": "#ff0000",
    "minecraft:shroomlight": "#993333",
    //"minecraft:yellow_candle": "#e5e533",
    "minecraft:deepslate_tile_wall": "#646464",
    "minecraft:glass_pane": "#0",
    "minecraft:chiseled_deepslate": "#646464",
    // "minecraft:cut_copper_slab": "#d87f33",
    "minecraft:dark_oak_trapdoor": "#664c33",
    "minecraft:mangrove_wall_sign": "#993333",
    // "minecraft:raw_copper_block": "#d87f33",
    "minecraft:beetroot": "#007c00",
    "minecraft:cyan_wool": "#4c7f99",
    "minecraft:horn_coral_block": "#e5e533",
    "minecraft:skull": "#0",
    //"minecraft:light_gray_candle_cake": "#0",
    //"minecraft:white_candle": "#c7c7c7",
    // "minecraft:element_95": "#7f4ccc",
    "minecraft:birch_planks": "#f7e9a3",
    "minecraft:sea_pickle": "#667f33",
    "minecraft:gray_shulker_box": "#4c4c4c",
    "minecraft:red_sandstone_stairs": "#d87f33",
    "minecraft:jungle_fence_gate": "#976d4d",
    // "minecraft:exposed_copper_grate": "#876b62",
    // "minecraft:waxed_copper_grate": "#d87f33",
    "minecraft:dead_brain_coral": "#4c4c4c",
    "minecraft:jungle_trapdoor": "#976d4d",
    "minecraft:spruce_wall_sign": "#815631",
    "minecraft:coal_block": "#191919",
    // "minecraft:element_79": "#828282",
    "minecraft:warped_fence_gate": "#3a8e8c",
    "minecraft:composter": "#8f7748",
    // "minecraft:waxed_double_cut_copper_slab": "#d87f33",
    // "minecraft:element_44": "#828282",
    // "minecraft:waxed_exposed_copper_door": "#876b62",
    "minecraft:blue_glazed_terracotta": "#334cb2",
    "minecraft:blue_wool": "#334cb2",
    "minecraft:clay": "#a4a8b8",
    "minecraft:weeping_vines": "#700200",
    "minecraft:chorus_plant": "#995acd",
    "minecraft:mud_brick_stairs": "#876b62",
    "minecraft:smooth_red_sandstone_stairs": "#d87f33",
    // "minecraft:element_100": "#7f4ccc",
    // "minecraft:element_103": "#7f4ccc",
    // "minecraft:element_105": "#828282",
    "minecraft:crimson_pressure_plate": "#700200",
    // "minecraft:element_106": "#828282",
    // "minecraft:element_107": "#828282",
    "minecraft:hard_gray_stained_glass_pane": "#0",
    // "minecraft:element_108": "#828282",
    // "minecraft:element_109": "#828282",
    "minecraft:light_gray_shulker_box": "#999999",
    // "minecraft:element_112": "#828282",
    // "minecraft:element_110": "#828282",
    // "minecraft:element_116": "#b2aa8c",
    // "minecraft:element_114": "#b2aa8c",
    "minecraft:white_glazed_terracotta": "#ffffff",
    "minecraft:stripped_warped_hyphae": "#562c3e",
    "minecraft:pumpkin_stem": "#007c00",
    "minecraft:lever": "#0",
    // "minecraft:element_50": "#b2aa8c",
    "minecraft:moving_block": "#707070",
    "minecraft:trapped_chest": "#8f7748",
    "minecraft:light_gray_concrete_powder": "#999999",
    "minecraft:brain_coral_block": "#f27fa5",
    "minecraft:standing_sign": "#8f7748",
    "minecraft:stone_block_slab4": "#707070",
    "minecraft:purple_concrete_powder": "#995acd",
    "minecraft:bamboo_planks": "#e5e533",
    "minecraft:command_block": "#664c33",
    "minecraft:twisting_vines": "#4c7f99",
    "minecraft:acacia_double_slab": "#d87f33",
    "minecraft:magma": "#700200",
    "minecraft:dirt": "#976d4d",
    "minecraft:reeds": "#007c00",
    "minecraft:deny": "#707070",
    "minecraft:bee_nest": "#e5e533",
    "minecraft:campfire": "#815631",
    "minecraft:stone_block_slab2": "#d87f33",
    "minecraft:stone_block_slab3": "#f7e9a3",
    "minecraft:dark_oak_pressure_plate": "#664c33",
    // "minecraft:element_28": "#828282",
    "minecraft:soul_soil": "#664c33",
    // "minecraft:element_8": "#7ab244",
    "minecraft:soul_sand": "#664c33",
    "minecraft:cobbled_deepslate_double_slab": "#646464",
    // "minecraft:element_86": "#ce7cfc",
    "minecraft:spruce_hanging_sign": "#815631",
    "minecraft:reinforced_deepslate": "#646464",
    "minecraft:end_rod": "#0",
    "minecraft:fletching_table": "#8f7748",
    "minecraft:cherry_leaves": "#f27fa5",
    "minecraft:black_glazed_terracotta": "#191919",
    // "minecraft:waxed_oxidized_cut_copper_stairs": "#167e86",
    "minecraft:stripped_acacia_log": "#d87f33",
    "minecraft:sniffer_egg": "#993333",
    "minecraft:warped_fence": "#4c7f99",
    "minecraft:cave_vines_body_with_berries": "#007c00",
    "minecraft:cherry_standing_sign": "#d1b1a1",
    "minecraft:mangrove_hanging_sign": "#993333",
    // "minecraft:element_32": "#ba8784",
    // "minecraft:waxed_exposed_copper_trapdoor": "#a7a7a7",
    //"minecraft:pink_candle": "#f27fa5",
    //"minecraft:brown_candle": "#664c33",
    // "minecraft:element_87": "#567ce5",
    "minecraft:mossy_stone_brick_stairs": "#707070",
    "minecraft:crimson_stem": "#943f61",
    "minecraft:colored_torch_rg": "#0",
    "minecraft:tuff_brick_double_slab": "#392923",
    "minecraft:vault": "#707070",
    "minecraft:azalea_leaves_flowered": "#007c00",
    // "minecraft:element_18": "#ce7cfc",
    "minecraft:crimson_slab": "#700200",
    "minecraft:warped_hyphae": "#562c3e",
    "minecraft:oxeye_daisy": "#007c00",
    "minecraft:bamboo_button": "#0",
    "minecraft:warped_wart_block": "#14b485",
    "minecraft:tuff_stairs": "#392923",
    "minecraft:yellow_carpet": "#e5e533",
    "minecraft:black_stained_glass": "#191919",
    // "minecraft:waxed_oxidized_copper_door": "#167e86",
    "minecraft:grass_block": "#92bc58",
    "minecraft:tripwire_hook": "#0",
    "minecraft:hard_black_stained_glass": "#191919",
    "minecraft:stripped_birch_log": "#f7e9a3",
    "minecraft:structure_block": "#999999",
    "minecraft:tinted_glass": "#4c4c4c",
    "minecraft:lime_wool": "#7fcc19",
    //"minecraft:blue_candle_cake": "#0",
    "minecraft:large_fern": "#007c00",
    "minecraft:sweet_berry_bush": "#007c00",
    // "minecraft:element_56": "#33a5c1",
    "minecraft:polished_blackstone_slab": "#191919",
    "minecraft:black_shulker_box": "#191919",
    // "minecraft:jungle_sapling": "#007c00",
    "minecraft:blue_concrete": "#334cb2",
    "minecraft:jungle_standing_sign": "#976d4d",
    // "minecraft:web": "#c7c7c7",
    "minecraft:lime_stained_glass_pane": "#0",
    "minecraft:cherry_double_slab": "#d1b1a1",
    // "minecraft:weathered_cut_copper_slab": "#3a8e8c",
    "minecraft:cocoa": "#007c00",
    "minecraft:dark_oak_leaves": "#3f5c18",
    "minecraft:orange_terracotta": "#9f5224",
    "minecraft:fire": "#ff0000",
    "minecraft:end_portal_frame": "#667f33",
    "minecraft:prismarine": "#4c7f99",
    //"minecraft:magenta_candle_cake": "#0",
    "minecraft:deepslate_gold_ore": "#646464",
    "minecraft:hard_orange_stained_glass": "#d87f33",
    "minecraft:glass": "#0",
    "minecraft:moss_block": "#667f33",
    // "minecraft:exposed_cut_copper": "#876b62",
    "minecraft:bookshelf": "#8f7748",
    // "minecraft:waxed_weathered_cut_copper_stairs": "#3a8e8c",
    "minecraft:mangrove_roots": "#815631",
    "minecraft:acacia_stairs": "#d87f33",
    "minecraft:polished_andesite_stairs": "#707070",
    "minecraft:cherry_slab": "#d1b1a1",
    "minecraft:polished_blackstone_pressure_plate": "#191919",
    "minecraft:sculk": "#0d1217",
    "minecraft:tuff_brick_stairs": "#392923",
    "minecraft:chemistry_table": "#ffffff",
    "minecraft:dead_fire_coral": "#4c4c4c",
    "minecraft:stone_brick_slab": "#707070",
    "minecraft:stripped_spruce_log": "#815631",
    // "minecraft:waxed_oxidized_copper_bulb": "#167e86",
    "minecraft:deepslate_brick_stairs": "#646464",
    "minecraft:warped_nylium": "#167e86",
    "minecraft:deepslate_emerald_ore": "#646464",
    "minecraft:stripped_crimson_stem": "#943f61",
    // "minecraft:acacia_sapling": "#007c00",
    "minecraft:cyan_shulker_box": "#4c7f99",
    "minecraft:unpowered_comparator": "#0",
    // "minecraft:element_37": "#567ce5",
    //"minecraft:lime_candle": "#7fcc19",
    "minecraft:target": "#ffffff",
    "minecraft:wooden_button": "#0",
    "minecraft:mangrove_door": "#993333",
    // "minecraft:weathered_copper_door": "#3a8e8c",
    "minecraft:pearlescent_froglight": "#f27fa5",
    "minecraft:double_stone_block_slab2": "#d87f33",
    "minecraft:double_stone_block_slab4": "#707070",
    "minecraft:tall_grass": "#007c00",
    "minecraft:nether_sprouts": "#4c7f99",
    // "minecraft:element_64": "#ef9ee2",
    "minecraft:cyan_stained_glass_pane": "#0",
    // "minecraft:element_92": "#7f4ccc",
    "minecraft:dead_horn_coral_block": "#4c4c4c",
    // "minecraft:element_12": "#33a5c1",
    "minecraft:dead_horn_coral_fan": "#4c4c4c",
    "minecraft:furnace": "#707070",
    "minecraft:warped_slab": "#4c7f99",
    "minecraft:netherrack": "#700200",
    "minecraft:warped_stem": "#3a8e8c",
    "minecraft:chain": "#0",
    "minecraft:horn_coral_fan": "#92bc58",
    "minecraft:green_shulker_box": "#667f33",
    "minecraft:brick_stairs": "#993333",
    "minecraft:purple_carpet": "#995acd",
    "minecraft:fire_coral_fan": "#92bc58",
    "minecraft:spruce_trapdoor": "#815631",
    "minecraft:purple_glazed_terracotta": "#995acd",
    // "minecraft:element_69": "#ef9ee2",
    "minecraft:chain_command_block": "#667f33",
    "minecraft:double_stone_block_slab": "#707070",
    // "minecraft:exposed_chiseled_copper": "#876b62",
    "minecraft:spruce_fence_gate": "#815631",
    "minecraft:red_nether_brick_stairs": "#700200",
    "minecraft:green_glazed_terracotta": "#667f33",
    "minecraft:deepslate_redstone_ore": "#646464",
    "minecraft:dead_brain_coral_block": "#4c4c4c",
    "minecraft:mangrove_fence": "#993333",
    "minecraft:birch_trapdoor": "#f7e9a3",
    "minecraft:tuff_bricks": "#392923",
    "minecraft:mud": "#575c5c",
    "minecraft:ice": "#a0a0ff",
    "minecraft:air": "#0",
    "minecraft:bed": "#993333",
    "minecraft:light_blue_wool": "#6699d8",
    "minecraft:black_concrete": "#191919",
    "minecraft:tnt": "#ff0000",
    "minecraft:dead_tube_coral_fan": "#4c4c4c",
    "minecraft:polished_diorite_stairs": "#fffcf5",
    "minecraft:orange_concrete": "#d87f33",
    "minecraft:netherreactor": "#a7a7a7",
    // "minecraft:element_83": "#b2aa8c",
    "minecraft:crying_obsidian": "#191919",
    "minecraft:lime_carpet": "#7fcc19",
    "minecraft:dead_fire_coral_fan": "#4c4c4c",
    // "minecraft:decorated_pot": "#8e3c2e",
    "minecraft:enchanting_table": "#993333",
    "minecraft:orange_tulip": "#007c00",
    "minecraft:azalea": "#007c00",
    "minecraft:bell": "#faee4d",
    "minecraft:mud_bricks": "#876b62",
    "minecraft:birch_wall_sign": "#f7e9a3",
    "minecraft:bamboo_wall_sign": "#e5e533",
    "minecraft:acacia_wood": "#4c4c4c",
    "minecraft:gray_stained_glass_pane": "#0",
    "minecraft:hopper": "#707070",
    "minecraft:hard_red_stained_glass": "#993333",
    "minecraft:lectern": "#8f7748",
    "minecraft:acacia_button": "#0",
    "minecraft:standing_banner": "#8f7748",
    "minecraft:sea_lantern": "#fffcf5",
    // "minecraft:waxed_oxidized_double_cut_copper_slab": "#167e86",
    "minecraft:light_blue_shulker_box": "#6699d8",
    "minecraft:jungle_stairs": "#976d4d",
    "minecraft:mangrove_propagule": "#007c00",
    "minecraft:birch_stairs": "#f7e9a3",
    "minecraft:spruce_slab": "#815631",
    "minecraft:blackstone_stairs": "#191919",
    "minecraft:blue_ice": "#a0a0ff",
    "minecraft:hard_red_stained_glass_pane": "#0",
    //"minecraft:purple_candle": "#995acd",
    "minecraft:lantern": "#a7a7a7",
    "minecraft:lit_blast_furnace": "#707070",
    // "minecraft:element_11": "#567ce5",
    "minecraft:dark_oak_fence": "#664c33",
    "minecraft:birch_door": "#f7e9a3",
    "minecraft:deepslate_lapis_ore": "#646464",
    "minecraft:crimson_hanging_sign": "#700200",
    "minecraft:deepslate_coal_ore": "#646464",
    // "minecraft:weathered_cut_copper": "#3a8e8c",
    "minecraft:bamboo_standing_sign": "#e5e533",
    "minecraft:stripped_mangrove_log": "#993333",
    "minecraft:polished_tuff": "#392923",
    "minecraft:magenta_stained_glass": "#b24cd8",
    // "minecraft:weathered_copper_bulb": "#3a8e8c",
    "minecraft:hard_white_stained_glass_pane": "#0",
    "minecraft:hard_cyan_stained_glass_pane": "#0",
    "minecraft:chiseled_nether_bricks": "#700200",
    "minecraft:warped_button": "#0",
    "minecraft:red_concrete_powder": "#993333",
    "minecraft:dead_bubble_coral": "#4c4c4c",
    // "minecraft:cherry_sapling": "#f27fa5",
    "minecraft:cherry_log": "#d1b1a1",
    "minecraft:cyan_concrete": "#4c7f99",
    "minecraft:polished_tuff_stairs": "#392923",
    "minecraft:dragon_egg": "#191919",
    "minecraft:nether_brick": "#700200",
    "minecraft:deepslate_iron_ore": "#646464",
    // "minecraft:element_23": "#828282",
    // "minecraft:element_3": "#567ce5",
    // "minecraft:element_22": "#828282",
    // "minecraft:element_2": "#ce7cfc",
    // "minecraft:element_25": "#828282",
    // "minecraft:element_5": "#ba8784",
    // "minecraft:element_24": "#828282",
    // "minecraft:element_4": "#33a5c1",
    // "minecraft:element_27": "#828282",
    // "minecraft:element_7": "#7ab244",
    // "minecraft:element_29": "#828282",
    // "minecraft:element_9": "#f9c654",
    "minecraft:camera": "#8f7748",
    // "minecraft:waxed_cut_copper": "#d87f33",
    "minecraft:cobbled_deepslate_slab": "#646464",
    // "minecraft:element_47": "#828282",
    "minecraft:lilac": "#007c00",
    "minecraft:crimson_standing_sign": "#700200",
    "minecraft:emerald_ore": "#707070",
    "minecraft:brown_mushroom_block": "#976d4d",
    "minecraft:petrified_oak_slab": "#8f7748",
    // "minecraft:element_61": "#ef9ee2",
    "minecraft:dropper": "#707070",
    //"minecraft:candle": "#f7e9a3",
    "minecraft:cobbled_deepslate_wall": "#646464",
    "minecraft:pointed_dripstone": "#0",
    "minecraft:red_carpet": "#993333",
    "minecraft:dark_prismarine_stairs": "#5cdbd5",
    "minecraft:chiseled_tuff_bricks": "#392923",
    "minecraft:red_tulip": "#007c00",
    "minecraft:chemical_heat": "#707070",
    "minecraft:trip_wire": "#0",
    "minecraft:cave_vines_head_with_berries": "#007c00",
    "minecraft:brick_slab": "#993333",
    "minecraft:brewing_stand": "#a7a7a7",
    // "minecraft:bamboo_sapling": "#8f7748",
    "minecraft:blast_furnace": "#707070",
    "minecraft:raw_iron_block": "#d8af93",
    "minecraft:dispenser": "#707070",
    "minecraft:crimson_roots": "#700200",
    "minecraft:acacia_slab": "#d87f33",
    "minecraft:stonecutter_block": "#707070",
    //"minecraft:white_candle_cake": "#0",
    "minecraft:end_portal": "#191919",
    "minecraft:jungle_double_slab": "#976d4d",
    "minecraft:spruce_wood": "#815631",
    "minecraft:blackstone": "#191919",
    "minecraft:lit_deepslate_redstone_ore": "#646464",
    // "minecraft:element_10": "#ce7cfc",
    // "minecraft:element_14": "#ba8784",
    // "minecraft:element_15": "#7ab244",
    // "minecraft:element_36": "#ce7cfc",
    // "minecraft:element_34": "#7ab244",
    // "minecraft:element_35": "#f9c654",
    // "minecraft:element_33": "#ba8784",
    // "minecraft:element_30": "#828282",
    // "minecraft:element_31": "#b2aa8c",
    // "minecraft:element_38": "#33a5c1",
    // "minecraft:element_59": "#ef9ee2",
    // "minecraft:element_54": "#ce7cfc",
    // "minecraft:element_55": "#567ce5",
    // "minecraft:element_57": "#ef9ee2",
    // "minecraft:element_53": "#f9c654",
    // "minecraft:element_48": "#828282",
    // "minecraft:element_45": "#828282",
    // "minecraft:element_42": "#828282",
    // "minecraft:element_40": "#828282",
    // "minecraft:element_70": "#ef9ee2",
    // "minecraft:element_71": "#ef9ee2",
    // "minecraft:element_76": "#828282",
    // "minecraft:element_74": "#828282",
    // "minecraft:element_75": "#828282",
    // "minecraft:element_78": "#828282",
    // "minecraft:element_65": "#ef9ee2",
    // "minecraft:element_60": "#ef9ee2",
    // "minecraft:element_63": "#ef9ee2",
    // "minecraft:element_90": "#7f4ccc",
    // "minecraft:element_94": "#7f4ccc",
    // "minecraft:element_96": "#7f4ccc",
    // "minecraft:element_88": "#33a5c1",
    // "minecraft:element_82": "#b2aa8c",
    // "minecraft:element_81": "#b2aa8c",
    // "minecraft:element_80": "#828282",
    "minecraft:lit_smoker": "#707070",
    "minecraft:smooth_quartz_stairs": "#fffcf5",
    "minecraft:light_gray_carpet": "#999999",
    "minecraft:purpur_block": "#b24cd8",
    "minecraft:cherry_wall_sign": "#d1b1a1",
    //"minecraft:cyan_candle": "#4c7f99",
    "minecraft:repeating_command_block": "#995acd",
    "minecraft:crimson_fungus": "#700200",
    "minecraft:cherry_planks": "#d1b1a1",
    "minecraft:polished_deepslate": "#646464",
    "minecraft:tuff_double_slab": "#392923",
    "minecraft:purpur_stairs": "#b24cd8",
    "minecraft:tube_coral": "#92bc58",
    // "minecraft:waxed_copper_door": "#d87f33",
    "minecraft:portal": "#0",
    "minecraft:peony": "#007c00",
    "minecraft:crafter": "#707070",
    "minecraft:spruce_planks": "#815631",
    "minecraft:amethyst_cluster": "#995acd",
    // "minecraft:waxed_chiseled_copper": "#d87f33",
    // "minecraft:waxed_cut_copper_slab": "#d87f33",
    "minecraft:dried_kelp_block": "#667f33",
    "minecraft:light_block": "#0",
    "minecraft:hard_light_gray_stained_glass": "#999999",
    "minecraft:crimson_fence": "#700200",
    "minecraft:chiseled_tuff": "#392923",
    "minecraft:lime_concrete_powder": "#7fcc19",
    "minecraft:birch_fence": "#f7e9a3",
    "minecraft:turtle_egg": "#f7e9a3",
    "minecraft:brown_terracotta": "#4c3223",
    "minecraft:deepslate_diamond_ore": "#646464",
    "minecraft:light_gray_wool": "#999999",
    "minecraft:soul_campfire": "#815631",
    "minecraft:wooden_pressure_plate": "#8f7748",
    "minecraft:white_concrete": "#ffffff",
    "minecraft:acacia_fence": "#d87f33",
    "minecraft:grass_path": "#976d4d",
    //"minecraft:orange_candle_cake": "#0",
    // "minecraft:weathered_copper": "#3a8e8c",
    "minecraft:lime_terracotta": "#677535",
    "minecraft:cherry_fence_gate": "#d1b1a1",
    "minecraft:gray_glazed_terracotta": "#4c4c4c",
    "minecraft:lodestone": "#ffffff",
    "minecraft:bamboo_mosaic": "#e5e533",
    "minecraft:purple_wool": "#995acd",
    "minecraft:iron_block": "#a7a7a7",
    "minecraft:ladder": "#0",
    "minecraft:cartography_table": "#8f7748"
  }
};
